// Copywrite: All Rights Reserved (c) 2023, Alex Kahn

export const SpecialValues = ["Unidentified"];

export const ModifierKeys = [
	"Alt",
	"AltGraph",
	"CapsLock",
	"Control",
	"Fn",
	"FnLock",
	"Hyper",
	"Meta",
	"NumLock",
	"ScrollLock",
	"Shift",
	"Super",
	"Symbol",
	"SymbolLock",
];

export const WhitespaceKeys = ["Enter", "Tab", " "];

export const NavigationKeys = [
	"ArrowDown",
	"ArrowLeft",
	"ArrowRight",
	"ArrowUp",
	"End",
	"Home",
	"PageDown",
	"PageUp",
];

export const EditingKeys = [
	"Backspace",
	"Clear",
	"Copy",
	"CrSel",
	"Cut",
	"Delete",
	"EraseEof",
	"ExSel",
	"Insert",
	"Paste",
	"Redo",
	"Undo",
];

export const UIKeys = [
	"Accept",
	"Again",
	"Attn",
	"Cancel",
	"ContextMenu",
	"Escape",
	"Execute",
	"Find",
	"Finish",
	"Help",
	"Pause",
	"Play",
	"Props",
	"Select",
	"ZoomIn",
	"ZoomOut",
];

export const DeviceKeys = [
	"BrightnessDown",
	"BrightnessUp",
	"Eject",
	"LogOff",
	"Power",
	"PowerOff",
	"PrintScreen",
	"Hibernate",
	"Standby",
	"WakeUp",
];

export const IMEKeys = [
	"AllCandidates",
	"Alphanumeric",
	"CodeInput",
	"Compose",
	"Convert",
	"Dead",
	"FinalMode",
	"GroupFirst",
	"GroupLast",
	"GroupNext",
	"GroupPrevious",
	"ModeChange",
	"NextCandidate",
	"NonConvert",
	"PreviousCandidate",
	"Process",
	"SingleCandidate",
];

export const KoreanKeys = ["HangulMode", "HanjaMode", "JunjaMode"];

export const JapaneseKeys = [
	"Eisu",
	"Hankaku",
	"Hiragana",
	"HiraganaKatakana",
	"KanaMode",
	"KanjiMode",
	"Katakana",
	"Romaji",
	"Zenkaku",
	"ZenkakuHanaku",
];

export const DeadKeysLinux = [
	"GDK_KEY_dead_grave",
	"Qt::Key_Dead_Grave",
	"GDK_KEY_dead_acute",
	"Qt::Key_Dead_Acute",
	"GDK_KEY_dead_circumflex",
	"Qt::Key_Dead_Circumflex",
	"GDK_KEY_dead_tilde",
	"Qt::Key_Dead_Tilde",
	"GDK_KEY_dead_perispomeni",
	"GDK_KEY_dead_macron",
	"Qt::Key_Dead_Macron",
	"GDK_KEY_dead_breve",
	"Qt::Key_Dead_Breve",
	"GDK_KEY_dead_abovedot",
	"Qt::Key_Dead_Abovedot",
	"GDK_KEY_dead_diaeresis",
	"Qt::Key_Dead_Diaeresis",
	"GDK_KEY_dead_abovering",
	"Qt::Key_Dead_Abovering",
	"GDK_KEY_dead_doubleacute",
	"Qt::Key_Dead_Doubleacute",
	"GDK_KEY_dead_caron",
	"Qt::Key_Dead_Caron",
	"GDK_KEY_dead_cedilla",
	"Qt::Key_Dead_Cedilla",
	"GDK_KEY_dead_ogonek",
	"Qt::Key_Dead_Ogonek",
	"GDK_KEY_dead_iota",
	"Qt::Key_Dead_Iota",
	"GDK_KEY_dead_voiced_sound",
	"Qt::Key_Dead_Voiced_Sound",
	"GDK_KEY_dead_semivoiced_sound",
	"Qt::Key_Dead_Semivoiced_Sound",
	"GDK_KEY_dead_belowdot",
	"Qt::Key_Dead_Belowdot",
	"GDK_KEY_dead_hook",
	"Qt::Key_Dead_Hook",
	"GDK_KEY_dead_horn",
	"Qt::Key_Dead_Horn",
	"GDK_KEY_dead_stroke",
	"GDK_KEY_dead_abovecomma",
	"GDK_KEY_dead_psili",
	"GDK_KEY_dead_abovereversedcomma",
	"GDK_KEY_dead_dasia",
	"GDK_KEY_dead_doublegrave",
	"GDK_KEY_dead_belowring",
	"GDK_KEY_dead_belowmacron",
	"GDK_KEY_dead_belowcircumflex",
	"GDK_KEY_dead_belowtilde",
	"GDK_KEY_dead_belowbreve",
	"GDK_KEY_dead_belowdiaeresis",
	"GDK_KEY_dead_invertedbreve",
	"GDK_KEY_dead_belowcomma",
	"GDK_KEY_dead_currency",
	"GDK_KEY_dead_a",
	"GDK_KEY_dead_A",
	"GDK_KEY_dead_e",
	"GDK_KEY_dead_E",
	"GDK_KEY_dead_i",
	"GDK_KEY_dead_I",
	"GDK_KEY_dead_o",
	"GDK_KEY_dead_O",
	"GDK_KEY_dead_u",
	"GDK_KEY_dead_U",
	"GDK_KEY_dead_small_schwa",
	"GDK_KEY_dead_capital_schwa",
	"GDK_KEY_dead_greek",
];

export const FunctionKeys = [
	"F1",
	"F2",
	"F3",
	"F4",
	"F5",
	"F6",
	"F7",
	"F8",
	"F9",
	"F10",
	"F11",
	"F12",
	"F13",
	"F14",
	"F15",
	"F16",
	"F17",
	"F18",
	"F19",
	"F20",
	"Soft1",
	"Soft2",
	"Soft3",
	"Soft4",
];

export const PhoneKeys = [
	"AppSwitch",
	"Call",
	"Camera",
	"CameraFocus",
	"EndCall",
	"GoBack",
	"GoHome",
	"HeadsetHook",
	"LastNumberRedial",
	"Notification",
	"MannerMode",
	"VoiceDial",
];

export const multiMediaKeys = [
	"ChannelDown",
	"ChannelUp",
	"MediaFastForward",
	"MediaPause",
	"MediaPlay",
	"MediaPlayPause",
	"MediaRecord",
	"MediaRewind",
	"MediaStop",
	"MediaTrackNext",
	"MediaTrackPrevious",
];

export const AudioKeys = [
	"AudioBalanceLeft",
	"AudioBalanceRight",
	"AudioBassDown",
	"AudioBassBoostDown",
	"AudioBassBoostToggle",
	"AudioBassBoostUp",
	"AudioBassUp",
	"AudioFaderFront",
	"AudioFaderRear",
	"AudioSurroundModeNext",
	"AudioTrebleDown",
	"AudioTrebleUp",
	"AudioVolumeDown",
	"AudioVolumeMute",
	"AudioVolumeUp",
	"MicrophoneToggle",
	"MicrophoneVolumeDown",
	"MicrophoneVolumeMute",
	"MicrophoneVolumeUp",
];

export const TVKeys = [
	"TV",
	"TV3DMode",
	"TVAntennaCable",
	"TVAudioDescription",
	"TVAudioDescriptionMixDown",
	"TVAudioDescriptionMixUp",
	"TVContentsMenu",
	"TVDataService",
	"TVInput",
	"TVInputComponent1",
	"TVInputComponent2",
	"TVInputComposite1",
	"TVInputComposite2",
	"TVInputHDMI1",
	"TVInputHDMI2",
	"TVInputHDMI3",
	"TVInputHDMI4",
	"TVInputVGA1",
	"TVMediaContext",
	"TVNetwork",
	"TVNumberEntry",
	"TVPower",
	"TVRadioService",
	"TVSatellite",
	"TVSatelliteBS",
	"TVSatelliteCS",
	"TVSatelliteToggle",
	"TVTerrestrialAnalog",
	"TVTerrestrialDigital",
	"TVTimer",
];

export const MediaControllerKeys = [
	"AVRInput",
	"AVRPower",
	"ColorF0Red",
	"ColorF1Green",
	"ColorF2Yellow",
	"ColorF3Blue",
	"ColorF4Grey",
	"ColorF5Brown",
	"ClosedCaptionToggle",
	"Dimmer",
	"DisplaySwap",
	"DVR",
	"Exit",
	"FavoriteClear0",
	"FavoriteClear1",
	"FavoriteClear2",
	"FavoriteClear3",
	"FavoriteRecall0",
	"FavoriteRecall1",
	"FavoriteRecall2",
	"FavoriteRecall3",
	"FavoriteStore0",
	"FavoriteStore1",
	"FavoriteStore2",
	"FavoriteStore3",
	"Guide",
	"GuideNextDay",
	"GuidePreviousDay",
	"Info",
	"InstantReplay",
	"Link",
	"ListProgram",
	"LiveContent",
	"Lock",
	"MediaApps",
	"MediaAudioTrack",
	"MediaLast",
	"MediaSkipBackward",
	"MediaSkipForward",
	"MediaStepBackward",
	"MediaStepForward",
	"MediaTopMenu",
	"NavigateIn",
	"NavigateNext",
	"NavigateOut",
	"NavigatePrevious",
	"NextFavoriteChannel",
	"NextUserProfile",
	"OnDemand",
	"Pairing",
	"PinPDown",
	"PinPMove",
	"PinPToggle",
	"PinPUp",
	"PlaySpeedDown",
	"PlaySpeedReset",
	"PlaySpeedUp",
	"RandomToggle",
	"RcLowBattery",
	"RecordSpeedNext",
	"RfBypass",
	"ScanChannelsToggle",
	"ScreenModeNext",
	"Settings",
	"SplitScreenToggle",
	"STBInput",
	"STBPower",
	"Subtitle",
	"Teletext",
	"VideoModeNext",
	"Wink",
	"ZoomToggle",
];

export const SpeechRecognitionKeys = [
	"SpeechCorrectionList",
	"SpeechInputToggle",
];

export const DocumentKeys = [
	"Close",
	"New",
	"Open",
	"Print",
	"Save",
	"SpellCheck",
	"MailForward",
	"MailReply",
	"MailSend",
];

export const ApplicationSelectorKeys = [
	"LaunchCalculator",
	"LaunchCalendar",
	"LaunchContacts",
	"LaunchMail",
	"LaunchMediaPlayer",
	"LaunchMusicPlayer",
	"LaunchMyComputer",
	"LaunchPhone",
	"LaunchScreenSaver",
	"LaunchSpreadsheet",
	"LaunchWebBrowser",
	"LaunchWebCam",
	"LaunchWordProcessor",
	"LaunchApplication1",
	"LaunchApplication2",
	"LaunchApplication3",
	"LaunchApplication4",
	"LaunchApplication5",
	"LaunchApplication6",
	"LaunchApplication7",
	"LaunchApplication8",
	"LaunchApplication9",
	"LaunchApplication10",
	"LaunchApplication11",
	"LaunchApplication12",
	"LaunchApplication13",
	"LaunchApplication14",
	"LaunchApplication15",
	"LaunchApplication16",
];

export const BrowserControlKeys = [
	"BrowserBack",
	"BrowserFavorites",
	"BrowserForward",
	"BrowserHome",
	"BrowserRefresh",
	"BrowserSearch",
	"BrowserStop",
];

export const KeyPadKeys = [
	"NumLock",
	"NumPad0",
	"NumPad1",
	"NumPad2",
	"NumPad3",
	"NumPad4",
	"NumPad5",
	"NumPad6",
	"NumPad7",
	"NumPad8",
	"NumPad9",
	"NumPadAdd",
	"NumPadBackspace",
	"NumPadClear",
	"NumPadClearEntry",
	"NumPadComma",
	"NumPadDecimal",
	"NumPadDivide",
	"NumPadEnter",
	"NumPadEqual",
	"NumPadHash",
	"NumPadMemoryAdd",
	"NumPadMemoryClear",
	"NumPadMemoryRecall",
	"NumPadMemoryStore",
	"NumPadMemorySubtract",
	"NumPadMultiply",
	"NumPadParenLeft",
	"NumPadParenRight",
	"NumPadStar",
	"NumPadSubtract",
	"Decimal",
	"Key11",
	"Key12",
	"Multiply",
	"Add",
	"Clear",
	"Divide",
	"Subtract",
	"Separator",
];

export const FarsiKeys = [
	"Farsi_0",
	"Farsi_1",
	"Farsi_2",
	"Farsi_3",
	"Farsi_4",
	"Farsi_5",
	"Farsi_6",
	"Farsi_7",
	"Farsi_8",
	"Farsi_9",
	"Farsi_yeh",
	"Farsi_Yeh",
	"Farsi_kaf",
	"Farsi_Kaf",
];

export const PersianKeys = [
	"Persian_0",
	"Persian_1",
	"Persian_2",
	"Persian_3",
	"Persian_4",
	"Persian_5",
	"Persian_6",
	"Persian_7",
	"Persian_8",
	"Persian_9",
	"Persian_yeh",
	"Persian_Yeh",
	"Persian_kaf",
	"Persian_Kaf",
];

export const NumberKeys = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];

export const SymbolKeys = [
	"!",
	"@",
	"#",
	"$",
	"%",
	"^",
	"&",
	"*",
	"(",
	")",
	"-",
	"_",
	"=",
	"+",
	"[",
	"{",
	"]",
	"}",
	"\\",
	"|",
	";",
	":",
	"'",
	'"',
	",",
	"<",
	".",
	">",
	"/",
	"?",
];

export const LetterKeys = [
	"a",
	"A",
	"b",
	"B",
	"c",
	"C",
	"d",
	"D",
	"e",
	"E",
	"f",
	"F",
	"g",
	"G",
	"h",
	"H",
	"i",
	"I",
	"j",
	"J",
	"k",
	"K",
	"l",
	"L",
	"m",
	"M",
	"n",
	"N",
	"o",
	"O",
	"p",
	"P",
	"q",
	"Q",
	"r",
	"R",
	"s",
	"S",
	"t",
	"T",
	"u",
	"U",
	"v",
	"V",
	"w",
	"W",
	"x",
	"X",
	"y",
	"Y",
	"z",
	"Z",
];

export const PreventDefaultKeysSet = new Set([
	...UIKeys,
	...NavigationKeys,
	...EditingKeys,
	...DeviceKeys,
	...ModifierKeys,
	...SpecialValues,
	"Tab",
]);

export const LetterKeysSet = new Set([...LetterKeys]);
export const NumberKeysSet = new Set([...NumberKeys]);

export const TypingKeysSet = new Set([
	...NumberKeys,
	...SymbolKeys,
	...LetterKeys,
]);

export const AllKeysSet = new Set([
	...SpecialValues,
	...ModifierKeys,
	...WhitespaceKeys,
	...NavigationKeys,
	...EditingKeys,
	...UIKeys,
	...DeviceKeys,
	...IMEKeys,
	...KoreanKeys,
	...JapaneseKeys,
	...DeadKeysLinux,
	...FunctionKeys,
	...PhoneKeys,
	...multiMediaKeys,
	...AudioKeys,
	...TVKeys,
	...MediaControllerKeys,
	...SpeechRecognitionKeys,
	...DocumentKeys,
	...ApplicationSelectorKeys,
	...BrowserControlKeys,
	...KeyPadKeys,
	...FarsiKeys,
	...PersianKeys,
	...NumberKeys,
	...SymbolKeys,
	...LetterKeys,
]);
